### ISSUE TITLE
Null reference exception after starting the download

### ISSUE THREAD

**Issue by raricy** [timsazon/arma-launcher#1]
#### Issue description
After starting the validating the mods and starting the download a messagebox appears followed by launcher crash

#### Steps to reproduce the issue

1. Open the launcher
2. Press validate and wait until it finishes
3. On the newly opened window with required mods press "Apply"

#### What's the expected result?

- The download starts properly

#### What's the actual result?

- Error appears and launcher crashes

#### Additional details / screenshot

- ![Screenshot](https://i.imgur.com/FaZ7GXC.png)

**Comment by timsazon** [comment]
Thank you for the [fix](https://github.com/timsazon/arma-launcher/commit/6831d6261ccb846de4cb023f44cdaac3763bca30)!
